# -*- coding: utf-8 -*-
"""Atividade_KNN_BreastCancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/SEU_LINK_AQUI
"""

# ============================================
# ATIVIDADE: KNN com Dataset Breast Cancer
# ============================================

# 1. IMPORTAÇÃO DAS BIBLIOTECAS
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Configurações
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("husl")

# 2. CARREGAMENTO DO DATASET
data = load_breast_cancer()
X = data.data
y = data.target

# INFORMAÇÕES GERAIS
print("=" * 50)
print("INFORMAÇÕES DO DATASET BREAST CANCER")
print("=" * 50)
print(f"\nShape da matriz de features: {X.shape}")
print(f"Número de amostras: {X.shape[0]}")
print(f"Número de features: {X.shape[1]}")
print(f"\nClasses: {data.target_names}")
print(f"Distribuição:")
print(f"  - Maligno (0): {np.sum(y == 0)} ({np.sum(y == 0)/len(y)*100:.1f}%)")
print(f"  - Benigno (1): {np.sum(y == 1)} ({np.sum(y == 1)/len(y)*100:.1f}%)")

# 3. GRÁFICOS EXPLORATÓRIOS
df = pd.DataFrame(X, columns=data.feature_names)
df['target'] = y
df['target_name'] = df['target'].map({0: 'Maligno', 1: 'Benigno'})

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
sns.histplot(data=df, x='mean radius', hue='target_name', kde=True, ax=axes[0], alpha=0.6)
axes[0].set_title('Distribuição do Raio Médio')
sns.histplot(data=df, x='mean area', hue='target_name', kde=True, ax=axes[1], alpha=0.6)
axes[1].set_title('Distribuição da Área Média')
plt.tight_layout()
plt.show()

# 4. PRÉ-PROCESSAMENTO (StandardScaler)
print("\n" + "=" * 50)
print("PRÉ-PROCESSAMENTO COM STANDARDSCALER")
print("=" * 50)
print("""
JUSTIFICATIVA:
O KNN usa distância Euclidiana. Sem padronização:
- Features com valores grandes (ex: área ~1000) dominam a distância
- Features com valores pequenos (ex: suavidade ~0.1) são ignoradas
- O algoritmo fica enviesado pelas unidades de medida

Com StandardScaler:
- Todas as features têm média 0 e desvio padrão 1
- Cada feature contribui igualmente
""")

# Divisão treino/teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# Aplicar scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 5. TREINAMENTO (K = 1 a 20)
print("\n" + "=" * 50)
print("TESTANDO VALORES DE K (1 a 20)")
print("=" * 50)

k_values = range(1, 21)
train_accuracies = []
test_accuracies = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)
    
    train_acc = accuracy_score(y_train, knn.predict(X_train_scaled))
    test_acc = accuracy_score(y_test, knn.predict(X_test_scaled))
    
    train_accuracies.append(train_acc)
    test_accuracies.append(test_acc)
    print(f"K = {k:2d} | Treino: {train_acc:.4f} | Teste: {test_acc:.4f}")

# 6. GRÁFICO ACURÁCIA × K
plt.figure(figsize=(12, 6))
plt.plot(k_values, train_accuracies, 'o-', label='Treino', linewidth=2)
plt.plot(k_values, test_accuracies, 's-', label='Teste', linewidth=2)
plt.xlabel('Valor de K')
plt.ylabel('Acurácia')
plt.title('Acurácia do KNN × K')
plt.legend()
plt.grid(True, alpha=0.3)
plt.xticks(k_values)

best_k = k_values[np.argmax(test_accuracies)]
best_accuracy = max(test_accuracies)
plt.axvline(x=best_k, color='red', linestyle='--', label=f'Melhor K = {best_k}')
plt.scatter(best_k, best_accuracy, color='red', s=200)
plt.legend()
plt.show()

# 7. ESCOLHA DO MELHOR K
print("\n" + "=" * 50)
print(f"MELHOR K ESCOLHIDO: K = {best_k}")
print(f"Acurácia no teste: {best_accuracy:.4f}")
print("=" * 50)

# 8. CLASSIFICATION REPORT FINAL
final_model = KNeighborsClassifier(n_neighbors=best_k)
final_model.fit(X_train_scaled, y_train)
y_pred = final_model.predict(X_test_scaled)

print("\nCLASSIFICATION REPORT - CONJUNTO DE TESTE:")
print(classification_report(y_test, y_pred, target_names=['Maligno', 'Benigno']))

# Matriz de confusão
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
            xticklabels=['Maligno', 'Benigno'],
            yticklabels=['Maligno', 'Benigno'])
plt.title(f'Matriz de Confusão - K={best_k}')
plt.xlabel('Predito')
plt.ylabel('Real')
plt.show()

print("\n✅ ATIVIDADE CONCLUÍDA!")